version: 2

updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: daily
    target-branch: dependabot-target
    open-pull-requests-limit: 100
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: daily
    target-branch: dependabot-target
    open-pull-requests-limit: 100
