name: Auto Merge Dependabot

on:
  workflow_run:
    workflows:
      - Check
      - 'Integration Test'
    types:
      - completed
  pull_request_target:
    branches:
      - update-dependencies
    types:
      - opened
      - reopened
      - synchronize

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - name: Merge
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        uses: ridedott/merge-me-action@v2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PRESET: DEPENDABOT_MINOR
