name: Create Dependabot target

on:
  delete:
    branches:
      - update-dependencies

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - name: Create Dependabot target branch
        uses: peterjgrainger/action-create-branch@v2.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: update-dependencies
